### ISSUE TITLE
clean --dist on Windows exits early with RPM error

### ISSUE THREAD

**Issue by maphew** [dave-shawley/setupext-janitor#12]
When running `clean --dist` on Windows 10, python 3.6, it exits early with _"error: don't know how to create RPM distributions on platform nt"_ and doesn't remove anything from `.\dists` folder. 

```
> python setup.py clean --dist
Creating entry_points for [OS name - system]: nt - Windows
c:\apps\miniconda3\envs\leo-dev\lib\site-packages\setuptools\dist.py:351: UserWarning: Normalizing '5.8.1-b1-dev1038' to '5.8.1b1.dev1038'
  normalized_version,
running clean
error: don't know how to create RPM distributions on platform nt
```

```
> dir dist /s/b
C:\Users\mattw\code\leo-editor\dist\leo-5.....
C:\Users\mattw\code\leo-editor\dist\leo-5.....
```

**Comment by maphew** [comment]
Just about the only place I've found that string is https://github.com/enthought/Python-2.7.3/blob/master/Lib/distutils/command/bdist_rpm.py. Strongly indicating an upstream problem. I've no idea how to get to the root of this one, so **help-wanted**! :) 

Why is it trying to do anything at all with RPM?  Where do I begin digging in?

**Comment by maphew** [comment]
With commit 3dca206 I've identified where the specific call within Janitor occurs, and what the name of the associated setuptools command is: `command.ensure_finalized()` immediately following `setuptools.command.bdist_rpm.bdist_rpm`. Don't know what to do with this info though.

```
> python setup.py clean --dist
running clean
--- start of if dist in cmd_name --
<setuptools.command.sdist.sdist object at 0x000001CD40186DA0>
passed command.ensure_finalized()
--- end of if dist in cmd_name --
--- start of if dist in cmd_name --
<distutils.command.bdist.bdist object at 0x000001CD4015E9B0>
passed command.ensure_finalized()
--- end of if dist in cmd_name --
--- start of if dist in cmd_name --
<distutils.command.bdist_dumb.bdist_dumb object at 0x000001CD40186C18>
passed command.ensure_finalized()
--- end of if dist in cmd_name --
--- start of if dist in cmd_name --
<setuptools.command.bdist_rpm.bdist_rpm object at 0x000001CD40186DD8>
error: don't know how to create RPM distributions on platform nt
```

**Comment by maphew** [comment]
Amazingly I actually did find a way to get the script to carry on but only by skipping over the error, which is not safe as it will skip all errors in this call. See b725529. 
```
> python setup.py clean --all
running clean
'build\lib' does not exist -- can't clean it
'build\bdist.win-amd64' does not exist -- can't clean it
'build\scripts-3.6' does not exist -- can't clean it

*** Exception encountered and ignored:
        <setuptools.command.bdist_rpm.bdist_rpm object at 0x000002191996ABA8>
        don't know how to create RPM distributions on platform nt

removing '.\__pycache__' (and everything under it)
removing '.\setupext_janitor\__pycache__' (and everything under it)
```

**Comment by maphew** [comment]
In 57b53d63af we finally get the full traceback which has been hidden from us so far:
```
> python setup.py clean --all
running clean
'build\lib' does not exist -- can't clean it
'build\bdist.win-amd64' does not exist -- can't clean it
'build\scripts-3.6' does not exist -- can't clean it

*** Exception encountered and ignored:
DistutilsPlatformError
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mattw\code\setupext-janitor\setupext_janitor\janitor.py", line 80, in run
    command.ensure_finalized()
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\command\bdist_rpm.py", line 200, in finalize_options
    "distributions on platform %s" % os.name)
distutils.errors.DistutilsPlatformError: don't know how to create RPM distributions on platform nt
--------------------------------------------------

removing '.\setupext_janitor\__pycache__' (and everything under it)
```

Strangely, if I try and narrow the exception catching so we're ONLY skipping DistutilsPlatformError  it turns into a name not defined error, and everything quits.

```
try:
    command.ensure_finalized()
except DistutilsPlatformError as e:
    ....
```


```
Traceback (most recent call last):
  File "C:\Users\mattw\code\setupext-janitor\setupext_janitor\janitor.py", line 80, in run
    command.ensure_finalized()
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\command\bdist_rpm.py", line 200, in finalize_options
    "distributions on platform %s" % os.name)
distutils.errors.DistutilsPlatformError: don't know how to create RPM distributions on platform nt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    'clean': janitor.CleanCommand,
  File "c:\apps\miniconda3\envs\set-jan\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\apps\miniconda3\envs\set-jan\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\mattw\code\setupext-janitor\setupext_janitor\janitor.py", line 81, in run
    except DistutilsPlatformError as e:
NameError: name 'DistutilsPlatformError' is not defined
```

Thank you to:
- https://stackoverflow.com/questions/3702675/how-to-print-the-full-traceback-without-halting-the-program
- https://stackoverflow.com/questions/18176602/how-to-get-name-of-exception-that-was-caught-in-python 

----

So, we have more information but still don't have a way of not hiding unrelated errors.

**Comment by maphew** [comment]
with 42508a6 we're finally skipping only this specific error and re-raising the exception if it's something else. I think it's ready for use.
